### ISSUE TITLE
Aggregate method Sum (or other) cannot be used in EF queries?

### ISSUE THREAD

**Issue by StefH** [NArnott/System.Linq.Dynamic#15]
This code:

```c#
// Entity:
public partial class KendoGrid_Employee
{
    public long Id { get; set; }
    public string Email { get; set; }    
}

// Code
var ctx = new KendoDatabaseEntities();
var result = ctx.KendoGrid_Employee.AsQueryable().Select("Sum(Id)").FirstOrDefault();
```
ErrorMessage:
**Additional information: No applicable method 'Sum' exists in type 'KendoGrid_Employee'**

The only way to get this working is by using this code?

```c#
var q1 = ctx.KendoGrid_Employee.AsQueryable().Select("new (\"__Key__\" as __Key__, Id, Email)");
var q2 = q1.GroupBy("__Key__");
var result = q2.Select("Sum(Id)").FirstOrDefault();
```

**Comment by StefH** [comment]
The other way to get this working is to use a dummy grouping to enable the aggregates to apply to the whole dataset.
See [dynamic-linq-aggregates-on-iqueryable-as-a-single-query](http://stackoverflow.com/questions/21634630/dynamic-linq-aggregates-on-iqueryable-as-a-single-query)

Example code:
```c#
var q1 = ctx.KendoGrid_Employee.AsQueryable().Select("new (Id, Email)");
var q2 = q1.GroupBy(x => 1);
var result = q2.Select("Sum(Id)").FirstOrDefault();
```

**Comment by NArnott** [comment]
On the service, I don't see why your original code wouldn't work.  Can you provide code for your KendoDatabaseEntities class?

**Comment by StefH** [comment]
**KendoDatabaseEntities** : this is just an EF context generated from database.

**Comment by NArnott** [comment]
Ok, so removing Dynamic Linq from the equation for a second, what you are trying to do is this:

    var result = ctx.KendoGrid_Employee.AsQueryable().Select(x => x.Id.Sum()).FirstOrDefault();

That doesn't make sense, and doesn't even compile.

What you want to do, I believe is something like this:

    var result = ctx.KendoGrid_Employee.AsQueryable().Select(x => x.Id).Sum();

Introduce Dynamic Linq back in, there is one way to do this out of the box:

    var result = ((IQueryable<int>)ctx.KendoGrid_Employee.AsQueryable().Select("Id")).Sum();

In order to avoid having to typecast the result of `Select`, I'm adding a `Sum` helper method to `BasicQueryable` so that Sum will work with `IQueryable.`  It will work like this in the **next release**:

    var result = ctx.KendoGrid_Employee.AsQueryable().Select("Id").Sum();
